apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: dev-team
  namespace: apps
spec:
  path: ./production
  patches:
    - patch: |-
        apiVersion: helm.toolkit.fluxcd.io/v2beta1
        kind: HelmRelease
        metadata:
          name: podinfo
          namespace: apps
        spec:
          values:
            replicaCount: 1
            ui:
              message: "This is store1-checkout"
      target:
        kind: HelmRelease
        name: podinfo
        namespace: apps