apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: dev-team1
  namespace: apps
spec:
  interval: 1m
  url: https://github.com/chenditc/multi-cluster-flux-example
  ref:
    branch: dev-team
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: dev-team1
  namespace: apps
spec:
  serviceAccountName: dev-team1
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: dev-team1
  prune: true
  validation: client


