apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: dev-team
  namespace: apps
spec:
  path: ./production
  patches:
    - patch: |-
        spec:
          values:
            replicaCount: 1
            ui:
              message: "This is store1-ai"
      target:
        kind: HelmRelease
        name: podinfo
        namespace: apps